use aiken/primitive/string

pub const treasury: ByteArray =
  #"d5434e727e2b5761e61e8aee4fbdfea3db9b5600a9d989eb7b7fa377"

pub const beadName: ByteArray = string.to_bytearray(@"BEAD")

pub const beadReferralName: ByteArray = string.to_bytearray(@"BEAD Referral")

pub const beadPolicyId: ByteArray =
  #"c0a89f985248796b8128d3f9cc7983bc0afb25d649741153f953f1c2"

pub const oraclePolicyId: ByteArray =
  #"cffbe5360fb26e813b34c05b222c37cdd9cf93760be436b107b13973"
