use aiken/primitive/string

pub const treasury: ByteArray =
  #"d5434e727e2b5761e61e8aee4fbdfea3db9b5600a9d989eb7b7fa377"

pub const beadName: ByteArray = string.to_bytearray(@"BEAD PREPROD")

pub const beadReferralName: ByteArray = string.to_bytearray(@"BEADR PREPROD")

pub const beadPolicyId: ByteArray =
  #"c8d5731cca17aa77b5f0daea78f433aef88f0fe01a89df02a6b72fea"

pub const oraclePolicyId: ByteArray =
  #"c008aa78aebf9e7728885fffcd40c2f64bd6290724a31d59159adaaa"
